#region File header

// // --------------------------------------------------------------------------------------------------------------------
// // <copyright file="ObjectFieldsCheckExtensions.cs" company="">
// //   Copyright 2014 Cyrille DUPUYDAUBY, Thomas PIERRAIN
// //   Licensed under the Apache License, Version 2.0 (the "License");
// //   you may not use this file except in compliance with the License.
// //   You may obtain a copy of the License at
// //       http://www.apache.org/licenses/LICENSE-2.0
// //   Unless required by applicable law or agreed to in writing, software
// //   distributed under the License is distributed on an "AS IS" BASIS,
// //   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// //   See the License for the specific language governing permissions and
// //   limitations under the License.
// // </copyright>
// // --------------------------------------------------------------------------------------------------------------------

#endregion

namespace NFluent
{
    /// <summary>
    ///     Kind of field (whether normal, generated by an auto-property, an anonymous class, etc.
    /// </summary>
    public enum FieldKind
    {
        /// <summary>
        ///     Normal field.
        /// </summary>
        Normal,

        /// <summary>
        ///     Field generated by an auto-property.
        /// </summary>
        AutoProperty,

        /// <summary>
        ///     Field generated by an anonymous class.
        /// </summary>
        AnonymousClass
    }
}